# Generated by Django 5.1.2 on 2024-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
